version: '2'

volumes:
  orderer0.example.com:

services:

  orderer0.example.com:
    container_name: orderer0.example.com
    restart: always
    image: hyperledger/fabric-orderer:1.4.4
    environment:
      - ORDERER_HOST=orderer0.example.com
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /etc/hyperledger
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ${PWD}/../FabricDemo/artifacts/channel:/etc/hyperledger/configtx
        - ${PWD}/../FabricDemo/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/:/etc/hyperledger/crypto/orderer
        - orderer0.example.com:/var/hyperledger/production/orderer

  cli.example.com:
    container_name: cli.example.com
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/artifacts
    extends:
      file: base.yaml
      service: cli-base
